# 配置文件应只包含CodeRabbit可解析的YAML格式内容
version: 1
language: zh-CN
settings:
  path_filters:
    - "!**/target/**"
    - "!**/.mvn/**"
    - "!**/*.md"
    - "!pom.xml"
  # 启用DDD相关检查
  checks:
    security: true
    performance: true
    readability: true
    architecture: true  # 启用架构检查

# 自定义规则（根据DDD规范配置）
rules:
  java:
    # 模块命名规范检查
    module-naming:
      regex: '^(.*-prd|.*-grp|.*-bc|zz-server)$'
      message: "模块命名不符合规范：项目级(-prd)、分组级(-grp)、限界上下文(-bc)、启动入口(zz-server)"
      severity: error
    
    # 包命名规范检查
    package-naming:
      regex: '^com\.zz\.[a-z]+prd\.[a-z]+bc\..*$'
      message: "包命名不符合规范：com.zz.项目名prd.[上下文名]bc..."
      severity: error
    
    # 类命名规范检查
    class-naming:
      patterns:
        - regex: '^.*AggregateRootEntity$'
          message: "聚合根实体应使用 XxxAggregateRootEntity 命名"
          severity: error
        - regex: '^.*DomainService$'
          message: "领域服务应使用 XxxDomainService 命名"
          severity: error
        # 其他类命名规则...
    
    # 禁止Domain层依赖外部层
    forbidden-dependencies:
      domain-packages:
        - "com.zz.*.domain"
      forbidden-packages:
        - "com.zz.*.northbound"
        - "com.zz.*.southbound"
        - "com.zz.*.infrastructure"
      message: "Domain层禁止依赖 northbound、southbound 或 infrastructure 层"
      severity: error
    
    # 禁止使用Manager/Helper等命名反模式
    forbidden-class-suffix:
      suffixes:
        - "Manager"
        - "Helper"
        - "Util"
        - "Processor"
      message: "避免使用模糊的类命名，建议重构为更精确的领域概念（如DomainService、Factory等）"
      severity: warning