# 配置文件应只包含CodeRabbit可解析的YAML格式内容
version: 1
language: zh-CN

# CodeRabbit审查配置
reviews:
  # 排除不想审查的文件和目录
  path_filters:
    - "!**/target/**"
    - "!**/.mvn/**"
    - "!**/*.md"
    - "!pom.xml"

  # 启用所有主要审查类别
  checks:
    security: true
    performance: true
    readability: true
    architecture: true

# 为AI审查员提供高级别的指导
# 告诉AI我们的项目规范在哪里，以及审查时需要特别关注什么
custom_instructions: |
  请严格遵循我们在 CONTRIBUTING.md 文件中定义的编码和架构规范。
  审查时请特别关注以下几点：
  1.  **命名规范**: 检查模块、包和类的命名是否符合DDD规范。例如，领域服务应以 `DomainService` 结尾，禁止使用 `Manager` 或 `Helper` 等后缀。
  2.  **分层依赖**: 确保 Domain 层的代码没有依赖 northbound, southbound 或 infrastructure 层的代码。如果发现不正确的依赖注入或类引用，请明确指出。
  3.  **DDD模式**: 检查代码是否正确使用了聚合、实体、值对象、领域服务等DDD模式。